-- Rode no SQL Editor do Supabase. Pode rodar mais de uma vez.
create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null, cat text not null, price numeric not null, old_price numeric,
  rating numeric default 4.5, color text default '#c9a962', avail text default 'Em estoque',
  tag text, image text, description text, move text default 'Automático', mat text default 'Aço',
  strap text default 'Aço', water text default '50m', size text default '41mm', sold integer default 0
);
create table if not exists orders (
  id text primary key, date text, items jsonb not null, total numeric not null,
  status text default 'Confirmado', created_at timestamptz default now()
);

-- Agora só o servidor (service role) acessa o banco. Sem policies = anon key não lê nem escreve nada.
alter table products enable row level security;
alter table orders enable row level security;
drop policy if exists "read_all" on products;
drop policy if exists "write_auth" on products;
drop policy if exists "update_auth" on products;
drop policy if exists "delete_auth" on products;
drop policy if exists "insert_all" on orders;
drop policy if exists "select_auth" on orders;

-- Catálogo inicial (só insere se a tabela estiver vazia)
do $$ begin
if not exists (select 1 from products) then
insert into products (name,cat,price,old_price,rating,color,avail,tag,description,move,mat,strap,water,size,sold) values
('SOVÍ Apex','Chronograph',4200,4800,4.8,'#c9a962','Em estoque','oferta','Um cronógrafo de precisão com acabamento em aço escovado, feito para quem mede o tempo em conquistas.','Automático','Aço escovado','Aço milanês','100m','42mm',210),
('SOVÍ Noir','Premium',6800,null,4.9,'#2b2b32','Em estoque','destaque','Silhueta escura e discreta, revestida em titânio preto — presença sem esforço.','Automático','Titânio preto','Couro italiano','50m','41mm',180),
('SOVÍ Velocity','Racing',3900,4500,4.6,'#8f3b3b','Em estoque','oferta','Inspirado nas pistas, com contadores de alta legibilidade e resposta instantânea.','Quartzo','Aço inoxidável','Borracha vulcanizada','100m','44mm',140),
('SOVÍ Ocean','Diver',4500,null,4.7,'#2e5f7a','Em estoque',null,'Certificado para profundidade, com moldura giratória unidirecional e luminescência de longa duração.','Automático','Aço inoxidável','Aço oyster','300m','43mm',160),
('SOVÍ Eclipse','Classic',3200,null,4.5,'#5a5248','Em estoque',null,'Linhas atemporais para quem prefere elegância discreta no dia a dia.','Automático','Aço polido','Couro preto','30m','40mm',95),
('SOVÍ Royale','Premium',8900,null,5.0,'#c9a962','Últimas unidades','destaque','A peça mais exclusiva da coleção — ouro rosé maciço e acabamento artesanal suíço.','Automático','Ouro rosé 18k','Couro alligator','50m','40mm',60),
('SOVÍ Chronos','Chronograph',5100,5600,4.7,'#9aa0a6','Em estoque','oferta','Três contadores, moldura taquimétrica e legibilidade impecável em qualquer luz.','Automático','Aço prateado','Aço prateado','100m','42mm',120),
('SOVÍ Vanguard','Sport',3600,null,4.4,'#4a4f56','Em estoque',null,'Leve, resistente e pronto para qualquer terreno — o companheiro esportivo da coleção.','Quartzo','Titânio','Borracha','200m','44mm',130),
('SOVÍ Meridian','Classic',2900,null,4.3,'#6b4a34','Em estoque',null,'Um clássico versátil, com mostrador limpo e proporções equilibradas.','Automático','Aço','Couro marrom','30m','39mm',88),
('SOVÍ Carbon','Racing',4700,5200,4.6,'#1c1c1f','Em estoque','oferta','Estrutura em fibra de carbono forjada — leveza extrema com resistência de pista.','Automático','Fibra de carbono','Borracha preta','100m','43mm',102),
('SOVÍ Imperial','Premium',9800,null,4.9,'#c0c0c0','Últimas unidades','limitado','Edição limitada em platina maciça — apenas poucas peças produzidas por ano.','Automático','Platina','Couro alligator','50m','40mm',40),
('SOVÍ Horizon','Diver',4100,null,4.5,'#2f6b4f','Em estoque',null,'Verde profundo e resistência de mergulho — feito para explorar sem pressa.','Automático','Aço','Aço','200m','42mm',115);
end if;
end $$;

-- Bucket público para as fotos dos produtos (o servidor envia; qualquer um só consegue LER a URL)
insert into storage.buckets (id, name, public) values ('products', 'products', true)
on conflict (id) do nothing;

-- Dados do cliente no pedido (nome, e-mail para o recibo, telefone opcional)
alter table orders add column if not exists customer_name text;
alter table orders add column if not exists customer_email text;
alter table orders add column if not exists customer_phone text;
